### ISSUE TITLE
All Need Rebase PR's dashboard is misleading or incorrect

### ISSUE THREAD

**Issue by spiffxp** [cncf/devstats.archive#37] opened 2017-12-29 15:46 UTC
I would expect "All Need Rebase PR's" to reflect the total number of open PR's that have the `needs-rebase` label applied on any given day

So for example, for kubernetes, I would expect the value for today to match the count returned by [this github query](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Akubernetes+label%3Aneeds-rebase) which as of writing this issue is 278.  The [All Need Rebase PR's dashboard](https://k8s.devstats.cncf.io/dashboard/db/all-need-rebase-prs?orgId=1&from=now-7d&to=now&var-period=d) shows 0.

**Comment by lukaszgryglicki** [comment] 2017-12-29 17:25
This `is:open is:pr user:kubernetes label:needs-rebase` GitHub query shows All open PRs that have `needs-rebase` label today. It is not filtering that label was applied today, additionally, this filters for `user = kubernetes` - I'm not sure what that means.
I'm quite sure that there are no 278 `need-rebase` label additions made today.

Anyway - I'll investigate `devstats` SQL query on Monday - it may have some issues too.

FYI: query that returns this data is: https://github.com/cncf/devstats/blob/master/metrics/kubernetes/all_prs_rebase.sql

`{{from}}` and `{{to}}`, {{n}} are replaced according to Period:
For example:
- For day `{{n}}` is 1, and from - to differ by day, incrementing by day
- For day `{{n}}` is 1, and from - to differ by week, incrementing by week
- For 7 days MA (moving average) `{{n}}` is 7, and from - to differ by week, incrementing by day.

**Comment by lukaszgryglicki** [comment] 2017-12-29 19:05
Actually, I can add "single stat" displaying the current value of PRs that needs rebase to this dashboard.

We can also think about more single stats that may be useful on the other dashboards (or new dashboards)?

I'm open to any suggestions...

**Comment by lukaszgryglicki** [comment] 2017-12-30 17:59
Actually would be great to get some list of "single stat" dashboards/metrics needed - for example as a "feature request" issue.
By "single stat" value I mean something updated each hour, like current number of open PRs, PRs that need rebase, failed test PRs, need CLA PRs, open issues, summary commits made, number of forks, stars, etc. etc. etc - there can be a ton of such single stat metrics to add...

**Comment by spiffxp** [comment] 2017-12-30 21:40
Right, so it sounds like the dashboard is "number of times the needs-rebase label was applied within a given interval."  Filtering for user:kubernetes is equivalent to querying for all repos within the kubernetes org.

I think what I'm asking for isn't the number of labels on a given day, but the aggregate/total of all PR's that have the label applied as of a given point in time.  The idea is to be able to look back historically and see whether the total number of 'needs-rebase' PR's is going up or down over time.

And yeah, this is probably something that applies to a number of statistics on devstats, I just haven't haven't spent time looking at how the data is queried.  Thanks for the pointer to the SQL.  It's easy to collect instantaneously for right now, and then store that going forward.   My dream though is some way to retroactively/historically derive this data, ie: the state of the world as of last year, last month, last week, etc.

**Comment by lukaszgryglicki** [comment] 2017-12-31 07:49
So I will create a new dashboard with number of open PRs that needed rebase historically (for example daily will show this value for today, yesterday, the day before yesterday and so on ...) and with single stat showing the current value, like for example in "PRs age": https://k8s.devstats.cncf.io/dashboard/db/prs-age?orgId=1

**Comment by lukaszgryglicki** [comment] 2018-01-02 10:26
I'm back on this: actually, this needs some time.
I will have to rewrite SQL probably and then regenerate data.
ETA - tomorrow.

**Comment by lukaszgryglicki** [comment] 2018-01-02 12:38
- [Need rebase PRs](https://k8s.devstats.cncf.io/dashboard/db/need-rebase-prs?orgId=1) needs the same changes per repo groups.

**Comment by lukaszgryglicki** [comment] 2018-01-02 13:07
This is problematic, because label needs-rebase is very often added and then removed from a PR.
If label is removed there is no such "event" in the database, so we don't "know" that label was removed later.
I need to think about something like detect PRs that ever had this label, and then check for future events to see if there are newer events for this PR that don't have "needs-rebase" label.
I'm investigating how to do it.

**Comment by lukaszgryglicki** [comment] 2018-01-02 13:44
BTW: provided GitHub query only search on "kubernetes" org, while DevStats collects data for 4 different orgs.
Seems like GitHub query doesn't support OR operator atm so I cannot compare results:
`is:open is:pr user:kubernetes label:needs-rebase` - this should be something like: `is:open is:pr (user:kubernetes or user:kubernetes-client or user:kubernetes-incubator or user:kubernetes-helm) label:needs-rebase`.

I have something that excludes PRs that had "needs-rebase" label but now don't have it - but it is still wip, my number are now too high, so I'm disassembling query into the simplest pieces and checking results - but GitHub queries cannot help me with it....

**Comment by lukaszgryglicki** [comment] 2018-01-02 17:21
Implemented (on the test server) chart that shows how many PRs had "needs-rebase" label on a given day (this is showing the number of such PRs that were open at that time and had the need-rebase label, after that day they can be closed or can have this label removed).
I've checked data and I'm quite sure it is OK.
But I'll double check tomorrow.

SQL is quite complex because "needs-rebase" label can be removed. So we cannot just detect open PRs (possibly closed later) that have this label. If we had a PR with this label we also have to change if that label wasn't removed later. This requires 3 temp tables, some min and max calls etc.

I think SQL is now OK, but *PLEASE* take a look - I could make a mistake. data is only on the test server. There is no single stat yet, will add tomorrow. The is a final `left join` that asks for null on the join table, to discard PRs that had need-rebase in the past but then label was removed.

SQL is here: 
- "All repos combined": https://github.com/cncf/devstats/blob/master/metrics/kubernetes/all_prs_rebase.sql
- "STacked by repository groups": https://github.com/cncf/devstats/blob/master/metrics/kubernetes/prs_rebase.sql

Dashboards only on the test server (will be on prod once I'm sure all is fine):
- https://k8s.cncftest.io/dashboard/db/all-need-rebase-prs?orgId=1
- https://k8s.cncftest.io/dashboard/db/need-rebase-prs?orgId=1

**Comment by spiffxp** [comment] 2018-01-02 18:16
As of today:
- 278 [`is:pr is:open user:kubernetes label:needs-rebase`](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Akubernetes+label%3Aneeds-rebase) (1957 closed)
- 8 [`is:pr is:open user:kubernetes-incubator label:needs-rebase`](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Akubernetes-incubator+label%3Aneeds-rebase) (12 closed)
- 0 [`is:pr is:open user:kubernetes-client label:needs-rebase`](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Akubernetes-client+label%3Aneeds-rebase) (0 closed)
- 0 [`is:pr is:open user:kubernetes-helm label:needs-rebase`](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Akubernetes-helm+label%3Aneeds-rebase) (0 closed)

So the values on your test server look high.  I can't seem to see more precision than "1K" but it looks close to 1.2K.  Additionally the "total" value in the legend doesn't make much sense for the "need-rebase-prs" dashboard

I really appreciate you digging into this.  I don't have time to look further at the SQL right now but I will see what I can do later today or tomorrow

**Comment by lukaszgryglicki** [comment] 2018-01-02 19:07
I know that value seems too high.
This is why it is on the test server only.
I'll dig tomorrow why it is so high .. currently no idea.
I'll also remove "total" value - this had a sense when we had values within periods. Now it doesn't have the sense as you pointed out. I've just overlooked this.

One of my ideas will be to count distinct PR numbers (now I'm counting PR IDs) - and then check those PRs manually. If I find any PR that doesn't have "needs-rebase" label or isn't open etc. - but my query list it - I will have some clue to investigate.

The problem is that I have to check state for "now" and there are > 1000 such PRs - while there should be about 270. So ... I need to hit one of 1000-270 "incorrect" ones.

**Comment by lukaszgryglicki** [comment] 2018-01-03 07:28
Back on this for analysis, no ETA - SQL analysis.

**Comment by lukaszgryglicki** [comment] 2018-01-03 08:04
Looks like I was looking at issue close date, and it seems like PR is often closed, while issue (which is fixed by this PR) isn't.

Numbers match now, will regenerate data and see.

**Comment by lukaszgryglicki** [comment] 2018-01-03 08:48
Seems like it was it, removed total value and added single stats:
https://k8s.cncftest.io/dashboard/db/need-rebase-prs?orgId=1
https://k8s.cncftest.io/dashboard/db/all-need-rebase-prs?orgId=1
 
It will be on prod soon, I need to add test coverage for complex cases like first adding `needs-rebase` label and then removing.

**Comment by lukaszgryglicki** [comment] 2018-01-03 10:49
OK, new Rebase dashboards also on production:
https://k8s.devstats.cncf.io/dashboard/db/need-rebase-prs?orgId=1
https://k8s.devstats.cncf.io/dashboard/db/all-need-rebase-prs?orgId=1

Added complex case test coverage in: https://github.com/cncf/devstats/commit/2f6c1a5f8fbc96725fc1d9ad34d309c77f34e703

Those lines test if there were other labels added: before, ath the same time, and after last time "needs-rebase" was applied:
https://github.com/cncf/devstats/blob/master/tests.yaml#L4098-L4100

Closing, please let me know if you want to reopen.

**Closed as completed by lukaszgryglicki** 2018-01-03 10:49 UTC

**Comment by spiffxp** [comment] 2018-01-03 17:43
Awesome!  This is perfect, thank you

**Comment by lukaszgryglicki** [comment] 2018-01-03 17:45
Thanks.
