### ISSUE TITLE
Don't use company specific dashboards for Kubernetes

### ISSUE THREAD

**Issue by nikhita** [cncf/devstats.archive#176] opened 2019-05-10 01:53 UTC
Context for this request: a new dashboard ["Company Commits Table"](https://all.devstats.cncf.io/d/56/company-commits-table?orgId=1) was recently developed for displaying company contributions with links to GitHub commits. To enable this for the Kubernetes devstats, it requires approval from the Kubernetes project.

---

One of the main Kubernetes community values is [**community > company**](https://github.com/kubernetes/community/blob/master/values.md#community-over-product-or-company). This means that we want to show emphasis on the community, rather than having a scenario which signifies something like "look how much this company owns this sig": https://k8s.devstats.cncf.io/d/55/company-prs-in-repository-groups?orgId=1.

With this in mind, we would:

- not like to opt-in to the new "Company Commits Table".
- also remove the existing company specific dashboards.

cc @spiffxp @parispittman @Phillels @cblecker @jberkus  for thoughts and concerns

**Comment by lukaszgryglicki** [comment] 2019-05-10 04:40
cc @dankohn 
Sure, but company-specific dashboards also show project's diversity, we also have `Independent` showing contributions from unaffiliated people.

**Comment by bgrant0607** [comment] 2019-05-12 04:16
@nikhita Information about company contributions is actually useful to both the CNCF and to the Kubernetes project, for a variety of reasons.

For CNCF, a diverse contributor base is one sign of project health.

For Kubernetes, it is one mechanism to incentivize companies to invest more in the project (recognition is a well known extrinsic motivator), and also a signal for us to reach out to companies that should invest more in the project, which we have done a number of times in the past.

I don't think having the data harms the community > company principle.

Whether the new dashboard is useful is another matter. I'm not sure what the intended purpose is.

**Comment by lukaszgryglicki** [comment] 2019-05-12 04:57
cc @dankohn @caniszczyk

**Comment by jberkus** [comment] 2019-05-12 16:46
Yes ... I find the original company graphs useful, for several reasons.  It's important for Contribex/SC to track whether (a) some companies with resources could be contributing more, and (b) whether particular SIGs are becoming very unbalanced when they shouldn't be.

However, I too am confused as to what the purpose of the new chart is.  It was requested by the CNCF.

**Comment by caniszczyk** [comment] 2019-05-12 17:35
Just to followup since I requested this, it's a very common request from organizations and CNCF members to understand:

1) what CNCF projects they contribute
2) who is contributing to these projects
3) when the last time they contributed

There are times this information was used for a legal purpose to understand which authorized contributors from a CLA were contributing to whether an organization was contributing to a particular project already (funny enough, for large companies this is sometimes hard to answer internally).

I have had to pull this information dozens of times manually and it's a bit painful. I don't think this violates community > company as we aren't comparing company contributions really, we are just trying to get an understanding of contributions across projects for organizations.

For very large companies, this is hard to do and having this in one place helps our community imho. Also there is no need for k8s to adopt this as we already get the info via the All DevStats but I think it's useful for organizations that may want to see what was their last activity.

**Comment by lukaszgryglicki** [comment] 2019-05-27 13:09
Should we close this?

**Comment by cblecker** [comment] 2019-05-27 15:00
@lukaszgryglicki Thanks for checking in, but no. This is still a topic of active discussion.

**Comment by lukaszgryglicki** [comment] 2019-05-27 15:01
OK, so just let me know.

**Comment by lizthegrey** [comment] 2019-10-21 16:11
This has just come up with @opentelemetry with some members trying to "shame" each other with inaccurate data :/ https://twitter.com/smflanders/status/1184981670103080960

cc @bhs

**Comment by lizthegrey** [comment] 2019-10-21 16:12
I would make the suggestion that disclaimers be added to the graphs indicating that they are potentially inaccurate, should not be used for comparing activity of companies, that there are other confounding factors such as company size, etc.

**Comment by bhs** [comment] 2019-10-21 20:54
(@lizthegrey thanks for the `@bhs` :)

There are at least two issues here:
- What these graphs say / don't say
- How OTel "members of standing" behave in regards to this sort of data

My overall feeling is that it's "net positive" to show the wide variety of OpenTelemetry employers. A common (and legitimate) complaint about much OSS software (especially "COSS" software) is that the committers all work for the same place... it is great for OTel to show that we're not one of those projects. :)

As for how OTel members communicate about other vendors: personally, I am also put off by messaging that portrays *any* committers to the project in a negative light. It may also help for there to be an "official" OpenTelemetry narrative about the genesis and/or leadership of the project... this could be a "sign on the wall" that we can all point to if a vendor is overstating their own role (rather than pointing at commit history, which is actually a _terrible_ metric for things like the spec where stability is an important property).

Maybe we can take this second aspect up on OTel/community, @lizthegrey ??

**Comment by iredelmeier** [comment] 2019-10-21 21:05
(Happy to move the OpenTelemetry-specific conversation elsewhere if that makes the most sense!)

I'm wondering if there's a potential happy medium that captures the list of companies over a given time period, without exposing the number of contributions or otherwise _ranking_ them?

**Comment by jberkus** [comment] 2019-10-21 22:25
Let's keep the discussion here, because the OpenTel issues are the same issues that folks have raised with other projects.

**Comment by tedsuo** [comment] 2019-10-21 23:53
I can see how this graph can both be useful, and misused. Beyond the obvious bad behavior that @lizthegrey pointed out, I could see a company trying to game-ify this to boost their numbers... ugh. At the end of the day, everything we're talking about is petty behavior, but it matters.

I suspect the answer lies not in limiting visibility into the projects in question, but in community standards. There are many other behaviors for which "sunlight is the best antiseptic," so I wouldn't want to obfuscate a project out of fear that the info could be misused. And while we could improve these metrics, even "perfect" metrics can be misused. So while I would not cry if this table went away, I'm also not sure that would be the correct approach for OpenTelemetry.

I do agree with @nikhita's (and k8's) statement that "community > company." I think that is very powerful. I suggest that we find a way to clarify the code of conduct – and develop a plan for appropriate remedial action – to handle when a company representative (not necessarily an engineer) presents themselves as a representative of a CNCF project, and in that light proceeds to engage in behavior which harms community involvement. For OpenTelemetry, this time it was related to metrics. But imho the issue is separate (and broader) than this particular instance.

**Closed as completed** 2020-09-14 05:42 UTC
Labels: blocked, discussion

**Comment by lizthegrey** [comment] 2020-09-14 06:21
https://www.splunk.com/en_us/blog/leadership/splunk-now-top-contributor-to-opentelemetry.html -- Splunk now issuing press releases based off the data

so, no, I don't think this issue is resolved :/

**Comment by lukaszgryglicki** [comment] 2020-09-14 06:34
Great news!
