### ISSUE TITLE
Affiliation not showing up as expected

### ISSUE THREAD

**Issue by dmcgowan** [cncf/devstats.archive#228] opened 2020-01-07 21:20 UTC
From the containerd devstats, one of our maintainers contributions don't seem to be reflected for their company.

See company contributions from the last year https://containerd.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20year&var-metric=contributions . Alibaba is listed with 3 contributions. 

See PR authors in the same time period https://containerd.devstats.cncf.io/d/22/prs-authors-table?orgId=1&var-period_name=Last%20year&var-repogroup_name=All and fuweid shows up with 58 PRs. The comments also show 400+ in the same time period.

I checked the github json and see
```
...
    "login": "fuweid",
    "email": "fuweid89!gmail.com",
    "affiliation": "Cheetah Mobile < 2015-11-01, Alibaba",
...
```

I have made updates to the cncf/gitdm for some other contributors, but not sure how to correct this one since the affiliation already seems correct.

**Comment by lukaszgryglicki** [comment] 2020-01-08 06:55
Thanks for reporting, I'll check that.

**Comment by lukaszgryglicki** [comment] 2020-01-14 07:25
Working on this, `gitdm` affiliations and the final JSON are indeed correct for `fuweid` so trying to track why the final dashboard data is not reflecting this.

**Comment by lukaszgryglicki** [comment] 2020-01-14 09:07
The problem is that actor with login `fuweid` (current) had `fhfuwei` in the past:

-->
detected that gha-actors PK is wrong: it is on (id) column while GitHub users *CAN* change user name leaving the same id (rename account) and then new user *CAN* pick no longer used login and it will have another id, so it is possible to have such (id, login) pairs: (1, "aaa"), (1, "bbb"), (2,"aaa") so key must be (id, login)!! This is very very dangerous and I must investigate that locally first on a real big database!

**Comment by lukaszgryglicki** [comment] 2020-01-14 09:42
So doing *FULL* `containerd` reinit locally to check if that primary key change won't break anything.

**Comment by lukaszgryglicki** [comment] 2020-01-14 12:34
Local reinit went good, will test that on the `test` k8s instance and finally will run on the `prod`.

**Comment by lukaszgryglicki** [comment] 2020-01-14 17:19
Fixed on the `test` server, `prod` data will be ready tomorrow. See `test` fixes:
- https://containerd.teststats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions
- https://containerd.teststats.cncf.io/d/21/prs-authors-companies-table?orgId=1&var-period_name=Last%20decade&var-repogroup_name=All
- https://containerd.teststats.cncf.io/d/56/company-commits-table?orgId=1&from=now-1y&to=now&var-repogroups=All&var-companies=Alibaba
- https://containerd.teststats.cncf.io/d/55/company-prs-in-repository-groups-table?orgId=1&var-period_name=Last%20decade&var-repogroups=All&var-companies=Alibaba&var-countries=All
- https://containerd.teststats.cncf.io/d/4/company-statistics-by-repository-group?orgId=1&var-period=w&var-metric=activity&var-repogroup_name=All&var-companies=%22Alibaba%22
- https://containerd.teststats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=Alibaba
- https://containerd.teststats.cncf.io/d/21/prs-authors-companies-table?orgId=1

**Comment by lukaszgryglicki** [comment] 2020-01-14 21:43
Prod data updates as well, closing this. Please reopen if needed.

**Closed as completed by lukaszgryglicki** 2020-01-14 21:43 UTC
Labels: wip, affiliations
